version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  
  pg_admin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    depends_on:
      - db
